### ISSUE TITLE
Serialization: Kotlin: [Internal Error] Source classes should be created separately before referencing

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/avro-kotlin#113]
## error:

```
Kotlin: [Internal Error] java.lang.IllegalStateException: Source classes should be created separately before referencing
	at org.jetbrains.kotlin.fir.backend.Fir2IrClassifierStorage.getIrClass(Fir2IrClassifierStorage.kt:217)
```

full stack trace attached.

Does not happen with maven console, but when compiling with IDEA ... and seems to affect only MacOs.

## Current Workarounds:

- build with maven
- exclude test folder of `avro-kotlin-serialization` from maven context.

## Related to:

- https://youtrack.jetbrains.com/issue/KT-68670/java.lang.IllegalStateException-Source-classes-should-be-created-separately-before-referencing
- https://youtrack.jetbrains.com/issue/KT-68565/K2-IllegalStateException-Source-classes-should-be-created-separately-before-referencing-with-new-IC-for-JPS

**Comment by jangalinski** [comment]
[scratch_30.txt](https://github.com/user-attachments/files/16726733/scratch_30.txt)

**Comment by zambrovski** [comment]
Currently fixed by setting Kotlin API version and Kotlin Language version to 1.9

**Comment by jangalinski** [comment]
Closed because this does not happen with language version 1.9 ...
