### ISSUE TITLE
Deserialize fails for inner classes - classForName does not match schema-fqn

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/avro-kotlin#138]
### Steps to reproduce

Use an inner serializable data class (`foo.MySchemas.Bar`) which has a schema fqn `foo.Bar` ... when we deserialize it, the default is to lookup the schema using the fingerprint and do a classForName lookup ... but this fails because class fqn and schema fqn differ.

### Expected behaviour

We can serialize/deserialize inner classes

### Possible Solutions:

a) use serializeName to mark the difference between schema and class - will probably not work because it is intended to work the other way around
b) use strategies to load class for schema-fqn, classForName being  the simple default. Other strategies could be classGraph scanning or generation of dictonary files where we resolve  fingerprint for class lookup

**Comment by zambrovski** [comment]
Proposed solution: drop the root object generation with nested data classes for types, but generate them as top level classes

**Comment by jangalinski** [comment]
We drop nested generation via #143 

so we can close this. It might become relevant once we deal with #144
